# Generated by Django 4.2.3 on 2023-07-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_categoria_image_categoria_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Noticia',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name_plural': 'Noticias'},
        ),
    ]
