# Generated by Django 4.2.3 on 2023-07-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='coemtario',
            new_name='comentario',
        ),
    ]
